### PR TITLE
Add github actions and fix styles

### PR DESCRIPTION
**Pull request by Virako**

### CODE REVIEW

**Comment by Virako** [comment]
The mypy analisys is not correct because there are several type hint that I do not know.

**Comment by Virako** [comment]
An important error is the dependency with fm_metamodels, mayebe the fm_metamodels should be inside core

**Comment by jagalindo** [comment]
> mayebe the fm_metamodels should be inside core

Not really. That would heavily limit the scope of the framework and will just reduce to fm analysis.

**Comment by jagalindo** [comment]
Please pr to the develop branch.

**Pull request closed without merging**
